# Generated by Django 4.1.2 on 2022-10-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0002_trainset_alter_userinfor_powerrights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfor",
            name="powerRights",
            field=models.SmallIntegerField(
                choices=[(0, "管理员"), (1, "用户")], verbose_name="权重"
            ),
        ),
    ]
