# Generated by Django 4.1.2 on 2022-10-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0003_alter_userinfor_powerrights"),
    ]

    operations = [
        migrations.RemoveField(model_name="trainset", name="imagesize",),
        migrations.AddField(
            model_name="trainset",
            name="file",
            field=models.FileField(
                default="", max_length=125, upload_to="train/", verbose_name="文件"
            ),
        ),
        migrations.AddField(
            model_name="trainset",
            name="imageheight",
            field=models.SmallIntegerField(default=8, verbose_name="图片高度（像素）"),
        ),
        migrations.AddField(
            model_name="trainset",
            name="imagewidth",
            field=models.SmallIntegerField(default=8, verbose_name="图片宽度（像素）"),
        ),
        migrations.AlterField(
            model_name="trainset",
            name="featurename",
            field=models.CharField(default="data", max_length=30, verbose_name="特征名"),
        ),
        migrations.AlterField(
            model_name="trainset",
            name="targetname",
            field=models.CharField(default="target", max_length=30, verbose_name="标签名"),
        ),
        migrations.AlterField(
            model_name="trainset",
            name="truename",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="真实标签名"
            ),
        ),
    ]
