# Generated by Django 4.1.2 on 2022-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0004_remove_trainset_imagesize_trainset_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainset",
            name="setstype",
            field=models.SmallIntegerField(
                choices=[(0, "训练集"), (1, "测试集"), (2, "验证集")],
                default=0,
                verbose_name="样本集类型",
            ),
        ),
    ]
