# Generated by Django 4.1.2 on 2022-10-16 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0005_trainset_setstype"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateField(verbose_name="上传时间")),
                ("upload_user", models.CharField(max_length=30, verbose_name="上传者")),
                (
                    "file",
                    models.FileField(
                        default="",
                        max_length=125,
                        upload_to="images/",
                        verbose_name="文件",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecogResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(default="KNN", max_length=30, verbose_name="算法名"),
                ),
                (
                    "paramers",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="参数"
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="评估值"
                    ),
                ),
                (
                    "datasets",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="picturerec.trainset",
                        verbose_name="数据集",
                    ),
                ),
                (
                    "picture_id",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="picturerec.uploadfilerecord",
                        verbose_name="文件",
                    ),
                ),
            ],
        ),
    ]
