# Generated by Django 4.1.2 on 2022-10-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0006_uploadfilerecord_recogresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainset",
            name="descreb",
            field=models.CharField(
                blank=True,
                default="手写体数据集",
                max_length=125,
                null=True,
                verbose_name="数据集描述",
            ),
        ),
    ]
