# Generated by Django 4.1.2 on 2022-10-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0007_trainset_descreb"),
    ]

    operations = [
        migrations.AddField(
            model_name="recogresult",
            name="user",
            field=models.CharField(default="", max_length=30, verbose_name="操作者"),
        ),
    ]
