# Generated by Django 4.1.2 on 2022-10-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0009_alter_recogresult_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="recogresult",
            name="create_time",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="计算时间"
            ),
        ),
    ]
