# Generated by Django 4.1.2 on 2022-10-19 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0010_recogresult_create_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recogresult", old_name="picture_id", new_name="picture",
        ),
    ]
