# Generated by Django 4.1.2 on 2022-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0012_alter_recogresult_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentsInfor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(0, "男"), (1, "女")], verbose_name="性别"
                    ),
                ),
                ("create_time", models.DateField(verbose_name="产生时间")),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
    ]
