# Generated by Django 4.1.2 on 2022-11-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0014_personinfor"),
    ]

    operations = [
        migrations.AddField(
            model_name="personinfor",
            name="isvalide",
            field=models.SmallIntegerField(
                choices=[(0, "否"), (1, "是")], default=0, verbose_name="有效"
            ),
        ),
        migrations.AlterField(
            model_name="personinfor",
            name="person_name",
            field=models.CharField(default="Tom", max_length=30, verbose_name="姓名"),
        ),
    ]
