# Generated by Django 4.1.2 on 2022-11-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0015_personinfor_isvalide_alter_personinfor_person_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonLandmarks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rects", models.CharField(max_length=125, verbose_name="面部位置")),
                ("landmarks", models.TextField(verbose_name="面部标注")),
                ("descriptions", models.TextField(verbose_name="面部描述")),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="picturerec.personinfor",
                        verbose_name="人物图片id",
                    ),
                ),
            ],
        ),
    ]
