# Generated by Django 4.1.2 on 2022-11-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0016_personlandmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="personinfor",
            name="descriptions",
            field=models.TextField(blank=True, verbose_name="面部描述"),
        ),
        migrations.AddField(
            model_name="personinfor",
            name="landmarks",
            field=models.TextField(blank=True, verbose_name="面部标注"),
        ),
        migrations.AddField(
            model_name="personinfor",
            name="rects",
            field=models.CharField(blank=True, max_length=125, verbose_name="面部位置"),
        ),
        migrations.DeleteModel(name="PersonLandmarks",),
    ]
