# Generated by Django 4.1.2 on 2022-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picturerec", "0017_personinfor_descriptions_personinfor_landmarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personinfor",
            name="rects",
            field=models.TextField(blank=True, verbose_name="面部位置"),
        ),
    ]
